# Generated by Django 5.2.17 on 2026-09-30 17:01

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Secuencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=10, verbose_name="Tipo")),
                ("anio", models.PositiveSmallIntegerField(verbose_name="Año")),
                (
                    "ultimo",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Último número"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Secuencia",
                "verbose_name_plural": "Secuencias",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("empresa", "tipo", "anio"), name="secuencia_unica"
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
    ]
