# Generated by Django 5.2.17 on 2026-09-30 17:40

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0002_perfilempresa_vendedores_ven_todos_los_clientes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre o razón social"
                    ),
                ),
                (
                    "rif",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="RIF / Cédula"
                    ),
                ),
                (
                    "contacto",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Persona de contacto"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo"
                    ),
                ),
                ("direccion", models.TextField(blank=True, verbose_name="Dirección")),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vendedor asignado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nombre"],
                "base_manager_name": "todos",
                "indexes": [
                    models.Index(
                        fields=["empresa", "vendedor"], name="cliente_empresa_vendedor"
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
    ]
