# Generated by Django 5.2.17 on 2026-10-08 02:46

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("empresas", "0006_ocultar_sin_stock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportacionClientes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_archivo",
                    models.CharField(max_length=200, verbose_name="Archivo"),
                ),
                ("contenido", models.BinaryField(verbose_name="Contenido")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ERRORES", "Con errores"),
                            ("VALIDADA", "Lista para importar"),
                            ("APLICADA", "Importada"),
                        ],
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                ("resumen", models.JSONField(default=dict, verbose_name="Resumen")),
                ("errores", models.JSONField(default=list, verbose_name="Errores")),
                ("avisos", models.JSONField(default=list, verbose_name="Avisos")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("aplicado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Importación de clientes",
                "verbose_name_plural": "Importaciones de clientes",
                "ordering": ["-creado_en"],
                "base_manager_name": "todos",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
    ]
