# Generated by Django 5.2.17 on 2026-10-07 12:03

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0005_formato_numero_presupuesto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deduccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80, verbose_name="Concepto")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Porcentaje (%)",
                    ),
                ),
                (
                    "base",
                    models.CharField(
                        choices=[
                            ("VENTA", "Sobre la venta"),
                            ("UTILIDAD", "Sobre la utilidad bruta"),
                        ],
                        default="VENTA",
                        max_length=8,
                        verbose_name="Se aplica",
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deducción",
                "verbose_name_plural": "Deducciones",
                "ordering": ["nombre", "pk"],
                "base_manager_name": "todos",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CostoFijo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80, verbose_name="Concepto")),
                (
                    "monto_usd",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Monto mensual (USD)",
                    ),
                ),
                ("desde", models.DateField(verbose_name="Desde el mes")),
                (
                    "hasta",
                    models.DateField(
                        blank=True, null=True, verbose_name="Hasta el mes"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Costo fijo",
                "verbose_name_plural": "Costos fijos",
                "ordering": ["nombre", "pk"],
                "base_manager_name": "todos",
                "indexes": [
                    models.Index(
                        fields=["empresa", "desde", "hasta"], name="costofijo_vigencia"
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
    ]
