# Generated by Django 5.2.17 on 2026-09-30 16:44

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
            ],
            options={
                "verbose_name": "Marca",
                "verbose_name_plural": "Marcas",
                "ordering": ["nombre"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INGRESO", "Ingreso"),
                            ("AJUSTE_POS", "Ajuste positivo"),
                            ("AJUSTE_NEG", "Ajuste negativo"),
                            ("BAJA_VENC", "Baja por vencimiento"),
                            ("APARTADO", "Apartado"),
                            ("LIBERACION", "Liberación de apartado"),
                            ("VENTA", "Venta"),
                        ],
                        max_length=12,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "cantidad",
                    models.IntegerField(
                        help_text="Positivo = entra, negativo = sale.",
                        verbose_name="Cantidad",
                    ),
                ),
                ("saldo_actual", models.IntegerField(verbose_name="Saldo del lote")),
                (
                    "saldo_apartado",
                    models.IntegerField(verbose_name="Apartado del lote"),
                ),
                (
                    "referencia_tipo",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Referencia"
                    ),
                ),
                (
                    "referencia_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="ID de referencia"
                    ),
                ),
                (
                    "motivo",
                    models.CharField(blank=True, max_length=250, verbose_name="Motivo"),
                ),
                (
                    "fecha",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
            ],
            options={
                "verbose_name": "Movimiento de inventario",
                "verbose_name_plural": "Movimientos de inventario",
                "ordering": ["-fecha", "-pk"],
                "base_manager_name": "todos",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, verbose_name="Código")),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "maneja_lotes",
                    models.BooleanField(
                        default=False, verbose_name="Maneja número de lote"
                    ),
                ),
                (
                    "maneja_vencimiento",
                    models.BooleanField(
                        default=False, verbose_name="Maneja fecha de vencimiento"
                    ),
                ),
                (
                    "precio_costo_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Costo (USD)",
                    ),
                ),
                (
                    "precio_venta_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Precio de venta (USD)",
                    ),
                ),
                (
                    "stock_minimo",
                    models.PositiveIntegerField(default=0, verbose_name="Stock mínimo"),
                ),
                (
                    "factor_venta_dias",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("30.00"),
                        help_text="Estimación de rotación: 30 = se vende 1 unidad cada 30 días; 0.5 = 2 unidades por día.",
                        max_digits=8,
                        verbose_name="Días por unidad vendida",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["nombre"],
                "base_manager_name": "todos",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Subcategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
            ],
            options={
                "verbose_name": "Subcategoría",
                "verbose_name_plural": "Subcategorías",
                "ordering": ["categoria__nombre", "nombre"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Unidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40, verbose_name="Nombre")),
                (
                    "abreviatura",
                    models.CharField(max_length=10, verbose_name="Abreviatura"),
                ),
            ],
            options={
                "verbose_name": "Unidad de medida",
                "verbose_name_plural": "Unidades de medida",
                "ordering": ["nombre"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["nombre"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Lote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_lote",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Número de lote"
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(blank=True, null=True, verbose_name="Vencimiento"),
                ),
                (
                    "cantidad_inicial",
                    models.PositiveIntegerField(verbose_name="Cantidad inicial"),
                ),
                (
                    "cantidad_actual",
                    models.IntegerField(verbose_name="Cantidad actual"),
                ),
                (
                    "cantidad_apartada",
                    models.IntegerField(default=0, verbose_name="Cantidad apartada"),
                ),
                (
                    "costo_unitario_usd",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Costo unitario (USD)",
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Fecha de ingreso",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote",
                "verbose_name_plural": "Lotes",
                "ordering": [
                    models.OrderBy(models.F("fecha_vencimiento"), nulls_last=True),
                    "fecha_ingreso",
                    "pk",
                ],
                "base_manager_name": "todos",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
    ]
