# Generated by Django 5.2.17 on 2026-09-30 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
        ("inventario", "0001_initial"),
        ("proveedores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lote",
            name="proveedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lotes",
                to="proveedores.proveedor",
                verbose_name="Proveedor",
            ),
        ),
        migrations.AddField(
            model_name="marca",
            name="empresa",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="empresas.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="empresa",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="empresas.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="lote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimientos",
                to="inventario.lote",
                verbose_name="Lote",
            ),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="productos",
                to="inventario.categoria",
                verbose_name="Categoría",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="empresa",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="empresas.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="marca",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productos",
                to="inventario.marca",
                verbose_name="Marca",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="proveedor_habitual",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productos",
                to="proveedores.proveedor",
                verbose_name="Proveedor habitual",
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lotes",
                to="inventario.producto",
                verbose_name="Producto",
            ),
        ),
        migrations.AddField(
            model_name="subcategoria",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategorias",
                to="inventario.categoria",
                verbose_name="Categoría",
            ),
        ),
        migrations.AddField(
            model_name="subcategoria",
            name="empresa",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="empresas.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="subcategoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productos",
                to="inventario.subcategoria",
                verbose_name="Subcategoría",
            ),
        ),
        migrations.AddField(
            model_name="unidad",
            name="empresa",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="empresas.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="unidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="productos",
                to="inventario.unidad",
                verbose_name="Unidad",
            ),
        ),
        migrations.AddConstraint(
            model_name="categoria",
            constraint=models.UniqueConstraint(
                fields=("empresa", "nombre"), name="categoria_unica_por_empresa"
            ),
        ),
        migrations.AddConstraint(
            model_name="marca",
            constraint=models.UniqueConstraint(
                fields=("empresa", "nombre"), name="marca_unica_por_empresa"
            ),
        ),
        migrations.AddIndex(
            model_name="movimientoinventario",
            index=models.Index(fields=["lote", "-fecha"], name="movimiento_lote_fecha"),
        ),
        migrations.AddConstraint(
            model_name="lote",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad_actual__gte", 0)),
                name="lote_actual_no_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="lote",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad_apartada__gte", 0)),
                name="lote_apartado_no_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="lote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cantidad_apartada__lte", models.F("cantidad_actual"))
                ),
                name="lote_apartado_no_supera_actual",
            ),
        ),
        migrations.AddConstraint(
            model_name="subcategoria",
            constraint=models.UniqueConstraint(
                fields=("categoria", "nombre"), name="subcategoria_unica"
            ),
        ),
        migrations.AddConstraint(
            model_name="unidad",
            constraint=models.UniqueConstraint(
                fields=("empresa", "abreviatura"), name="unidad_unica_por_empresa"
            ),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(
                fields=["empresa", "activo", "nombre"],
                name="producto_empresa_activo_nombre",
            ),
        ),
        migrations.AddConstraint(
            model_name="producto",
            constraint=models.UniqueConstraint(
                fields=("empresa", "codigo"), name="producto_codigo_unico_por_empresa"
            ),
        ),
    ]
