# Generated by Django 5.2.17 on 2026-10-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0004_importacionproductos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimientoinventario",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("INGRESO", "Ingreso"),
                    ("AJUSTE_POS", "Ajuste positivo"),
                    ("AJUSTE_NEG", "Ajuste negativo"),
                    ("BAJA_VENC", "Baja por vencimiento"),
                    ("APARTADO", "Apartado"),
                    ("LIBERACION", "Liberación de apartado"),
                    ("VENTA", "Venta"),
                    ("DEVOLUCION", "Devolución de cliente"),
                ],
                max_length=12,
                verbose_name="Tipo",
            ),
        ),
    ]
