# Generated by Django 5.2.17 on 2026-10-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0006_unidades_laboratorio"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="exento_iva",
            field=models.BooleanField(
                default=False,
                help_text="No se le calcula IVA y sale marcado (E) en los documentos.",
                verbose_name="Exento de IVA",
            ),
        ),
    ]
