# Generated by Django 5.2.17 on 2026-09-30 16:27

import apps.empresas.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Se usa en rutas internas y carpetas de Cloudinary.",
                        max_length=60,
                        unique=True,
                        verbose_name="Identificador",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVA", "Activa"), ("SUSPENDIDA", "Suspendida")],
                        default="ACTIVA",
                        max_length=12,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("PRUEBA", "Prueba"),
                            ("BASICO", "Básico"),
                            ("PRO", "Pro"),
                        ],
                        default="PRUEBA",
                        max_length=10,
                        verbose_name="Plan",
                    ),
                ),
                (
                    "activa_hasta",
                    models.DateField(
                        blank=True,
                        help_text="Vacío = sin vencimiento.",
                        null=True,
                        verbose_name="Activa hasta",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="PerfilEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_comercial",
                    models.CharField(max_length=150, verbose_name="Nombre comercial"),
                ),
                (
                    "razon_social",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Razón social"
                    ),
                ),
                (
                    "rif",
                    models.CharField(blank=True, max_length=20, verbose_name="RIF"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="PNG o JPG, máximo 2 MB. Se usa en la app y en los documentos.",
                        upload_to=apps.empresas.models._ruta_logo,
                        verbose_name="Logo",
                    ),
                ),
                (
                    "logo_pdf",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        upload_to=apps.empresas.models._ruta_logo,
                        verbose_name="Logo para PDF",
                    ),
                ),
                (
                    "color_principal",
                    models.CharField(
                        default="#053D74",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$", "Usa un color en formato #RRGGBB."
                            )
                        ],
                        verbose_name="Color principal",
                    ),
                ),
                (
                    "direccion_fiscal",
                    models.TextField(blank=True, verbose_name="Dirección fiscal"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Teléfono"
                    ),
                ),
                (
                    "telefono_2",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Teléfono 2"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo"
                    ),
                ),
                (
                    "sitio_web",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Sitio web"
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Instagram"
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="WhatsApp"
                    ),
                ),
                (
                    "prefijo_numeracion",
                    models.CharField(
                        blank=True,
                        help_text="Ej: BL → BL202600001",
                        max_length=6,
                        verbose_name="Prefijo de numeración",
                    ),
                ),
                (
                    "condiciones_presupuesto",
                    models.TextField(
                        blank=True,
                        default="Precios sujetos a la tasa del día de emisión. Validez según fecha indicada.",
                        verbose_name="Condiciones del presupuesto",
                    ),
                ),
                (
                    "pie_documentos",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="Pie de página de documentos",
                    ),
                ),
                (
                    "datos_bancarios",
                    models.TextField(
                        blank=True, verbose_name="Datos bancarios / pago móvil"
                    ),
                ),
                (
                    "firma",
                    models.ImageField(
                        blank=True,
                        help_text="Opcional. PNG con fondo transparente.",
                        upload_to=apps.empresas.models._ruta_firma,
                        verbose_name="Firma o sello",
                    ),
                ),
                (
                    "iva_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("16.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="IVA por defecto (%)",
                    ),
                ),
                (
                    "dias_validez_presupuesto",
                    models.PositiveSmallIntegerField(
                        default=7, verbose_name="Validez del presupuesto (días)"
                    ),
                ),
                (
                    "dias_apartado",
                    models.PositiveSmallIntegerField(
                        default=15, verbose_name="Días de apartado"
                    ),
                ),
                (
                    "modo_precio",
                    models.CharField(
                        choices=[
                            ("FIJO", "Fijo: lo define el administrador"),
                            ("LIBRE", "Libre: lo define el vendedor"),
                            ("RANGO", "Rango: el vendedor elige dentro de un margen"),
                        ],
                        default="RANGO",
                        max_length=6,
                        verbose_name="Modo de precios",
                    ),
                ),
                (
                    "margen_minimo_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Margen mínimo sobre costo (%)",
                    ),
                ),
                (
                    "margen_maximo_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Vacío = sin tope.",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Margen máximo sobre costo (%)",
                    ),
                ),
                (
                    "requiere_validacion",
                    models.BooleanField(
                        default=True, verbose_name="Las ventas requieren validación"
                    ),
                ),
                (
                    "comision_requiere_pago",
                    models.BooleanField(
                        default=False, verbose_name="La comisión exige venta cobrada"
                    ),
                ),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de empresa",
                "verbose_name_plural": "Perfiles de empresa",
            },
        ),
        migrations.CreateModel(
            name="Membresia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("DUENO", "Dueño"),
                            ("ADMIN", "Administrador"),
                            ("ALMACEN", "Almacén"),
                            ("VENDEDOR", "Vendedor"),
                        ],
                        default="VENDEDOR",
                        max_length=10,
                        verbose_name="Rol",
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membresias",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membresias",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membresía",
                "verbose_name_plural": "Membresías",
                "ordering": ["empresa__nombre", "usuario__email"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "empresa"), name="membresia_unica"
                    )
                ],
            },
        ),
    ]
