# Generated by Django 5.2.17 on 2026-09-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilempresa",
            name="vendedores_ven_todos_los_clientes",
            field=models.BooleanField(
                default=False,
                help_text="Si está apagado, cada vendedor ve solo los clientes que creó o tiene asignados.",
                verbose_name="Los vendedores ven todos los clientes",
            ),
        ),
    ]
