# Generated by Django 5.2.17 on 2026-09-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0002_perfilempresa_vendedores_ven_todos_los_clientes"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="limite_usuarios",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Vacío = sin límite.",
                null=True,
                verbose_name="Límite de usuarios activos",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="notas",
            field=models.TextField(
                blank=True, verbose_name="Notas internas (solo plataforma)"
            ),
        ),
    ]
