# Generated by Django 5.2.17 on 2026-10-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0003_empresa_limite_usuarios_empresa_notas"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membresia",
            options={
                "ordering": ["empresa__nombre", "usuario__username"],
                "verbose_name": "Membresía",
                "verbose_name_plural": "Membresías",
            },
        ),
    ]
