# Generated by Django 5.2.17 on 2026-10-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0004_alter_membresia_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilempresa",
            name="formato_numero_presupuesto",
            field=models.CharField(
                choices=[
                    ("GUION", "P-2026-00001 (con prefijo)"),
                    ("CORRIDO", "202600001 (año + correlativo)"),
                ],
                default="GUION",
                help_text='El correlativo reinicia cada año. "Año + correlativo" continúa después del último número existente.',
                max_length=8,
                verbose_name="Numeración de presupuestos",
            ),
        ),
    ]
