# Generated by Django 5.2.17 on 2026-10-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0005_formato_numero_presupuesto"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilempresa",
            name="ocultar_sin_stock",
            field=models.BooleanField(
                default=False,
                help_text="Para empresas que presupuestan productos que aún no tienen en inventario. El aviso sigue viéndose dentro de Ordo.",
                verbose_name="No mostrar «SIN STOCK» en los PDF",
            ),
        ),
    ]
