# Generated by Django 5.2.17 on 2026-09-30 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TasaCambio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(unique=True, verbose_name="Fecha")),
                (
                    "bs_por_usd",
                    models.DecimalField(
                        decimal_places=4, max_digits=14, verbose_name="Bs por USD"
                    ),
                ),
                (
                    "fuente",
                    models.CharField(
                        choices=[("BCV", "BCV automático"), ("MANUAL", "Carga manual")],
                        default="BCV",
                        max_length=8,
                        verbose_name="Fuente",
                    ),
                ),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "registrada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tasa de cambio",
                "verbose_name_plural": "Tasas de cambio",
                "ordering": ["-fecha"],
            },
        ),
    ]
