# Generated by Django 5.2.17 on 2026-09-30 17:05

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
        ("inventario", "0004_importacionproductos"),
        ("proveedores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdenCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=30, verbose_name="Número")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("ENVIADA", "Enviada al proveedor"),
                            ("PARCIAL", "Recibida parcialmente"),
                            ("RECIBIDA", "Recibida"),
                            ("ANULADA", "Anulada"),
                        ],
                        default="BORRADOR",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True, verbose_name="Fecha")),
                (
                    "fecha_envio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Enviada el"
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True, verbose_name="Notas para el proveedor"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes",
                        to="proveedores.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de compra",
                "verbose_name_plural": "Órdenes de compra",
                "ordering": ["-creado_en", "-pk"],
                "base_manager_name": "todos",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ItemOrdenCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_pedida",
                    models.PositiveIntegerField(verbose_name="Cantidad pedida"),
                ),
                (
                    "cantidad_recibida",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Cantidad recibida"
                    ),
                ),
                (
                    "costo_unitario_usd",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Costo unitario (USD)",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventario.producto",
                    ),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="compras.ordencompra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de orden de compra",
                "verbose_name_plural": "Ítems de orden de compra",
                "ordering": ["producto__nombre"],
                "base_manager_name": "todos",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="ordencompra",
            constraint=models.UniqueConstraint(
                fields=("empresa", "numero"), name="orden_compra_numero_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemordencompra",
            constraint=models.UniqueConstraint(
                fields=("orden", "producto"), name="item_oc_producto_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemordencompra",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cantidad_recibida__lte", models.F("cantidad_pedida"))
                ),
                name="item_oc_no_recibe_de_mas",
            ),
        ),
    ]
