# Generated by Django 5.2.17 on 2026-09-30 16:44

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "rif",
                    models.CharField(blank=True, max_length=20, verbose_name="RIF"),
                ),
                (
                    "contacto",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Persona de contacto"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo"
                    ),
                ),
                ("direccion", models.TextField(blank=True, verbose_name="Dirección")),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "ordering": ["nombre"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("empresa", "nombre"),
                        name="proveedor_nombre_unico_por_empresa",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
    ]
