# Generated by Django 5.2.17 on 2026-09-30 19:00

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0002_perfilempresa_vendedores_ven_todos_los_clientes"),
        ("inventario", "0004_importacionproductos"),
        ("ventas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(verbose_name="Fecha de la venta (validación)"),
                ),
                (
                    "base_usd",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Base (sin IVA)"
                    ),
                ),
                (
                    "monto_usd",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Comisión"
                    ),
                ),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "presupuesto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comision",
                        to="ventas.presupuesto",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Comisión",
                "verbose_name_plural": "Comisiones",
                "ordering": ["-fecha", "-pk"],
                "base_manager_name": "todos",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="LineaComision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_usd", models.DecimalField(decimal_places=2, max_digits=14)),
                ("porcentaje", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "origen",
                    models.CharField(
                        choices=[("VENDEDOR", "Vendedor"), ("CATEGORIA", "Categoría")],
                        max_length=10,
                    ),
                ),
                ("monto_usd", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "comision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="comisiones.comision",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ventas.itempresupuesto",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "base_manager_name": "todos",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Liquidacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=30, verbose_name="Número")),
                ("hasta", models.DateField(verbose_name="Ventas validadas hasta")),
                (
                    "total_usd",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="Total"
                    ),
                ),
                ("creada_en", models.DateTimeField(default=django.utils.timezone.now)),
                ("pagada", models.BooleanField(default=False, verbose_name="Pagada")),
                ("anulada", models.BooleanField(default=False, verbose_name="Anulada")),
                (
                    "fecha_pago",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de pago"
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Método de pago"
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Referencia"
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "creada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidación",
                "verbose_name_plural": "Liquidaciones",
                "ordering": ["-creada_en", "-pk"],
                "base_manager_name": "todos",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="comision",
            name="liquidacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comisiones",
                to="comisiones.liquidacion",
            ),
        ),
        migrations.CreateModel(
            name="PorcentajeCategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Comisión (%)"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="inventario.categoria",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Excepción por categoría",
                "verbose_name_plural": "Excepciones por categoría",
                "base_manager_name": "todos",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PorcentajeVendedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Comisión (%)"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Porcentaje por vendedor",
                "verbose_name_plural": "Porcentajes por vendedor",
                "base_manager_name": "todos",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="liquidacion",
            constraint=models.UniqueConstraint(
                fields=("empresa", "numero"), name="liquidacion_numero_unico"
            ),
        ),
        migrations.AddIndex(
            model_name="comision",
            index=models.Index(
                fields=["empresa", "vendedor", "liquidacion"],
                name="comision_vendedor_liq",
            ),
        ),
        migrations.AddConstraint(
            model_name="porcentajecategoria",
            constraint=models.UniqueConstraint(
                fields=("empresa", "categoria"), name="comision_pct_categoria_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="porcentajevendedor",
            constraint=models.UniqueConstraint(
                fields=("empresa", "vendedor"), name="comision_pct_vendedor_unico"
            ),
        ),
    ]
