# Generated by Django 5.2.17 on 2026-10-01 17:12

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comisiones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AjusteComision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha de la devolución")),
                (
                    "monto_usd",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Ajuste (negativo)",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "comision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ajustes",
                        to="comisiones.comision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ajuste de comisión",
                "verbose_name_plural": "Ajustes de comisión",
                "ordering": ["-fecha", "-pk"],
                "base_manager_name": "todos",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
    ]
