# Generated by Django 5.2.17 on 2026-10-01 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comisiones", "0002_ajustecomision"),
        ("empresas", "0004_alter_membresia_options"),
        ("ventas", "0002_devoluciones"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ajustecomision",
            name="devolucion",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ajuste_comision",
                to="ventas.devolucion",
            ),
        ),
        migrations.AddField(
            model_name="ajustecomision",
            name="empresa",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="empresas.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="ajustecomision",
            name="liquidacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ajustes",
                to="comisiones.liquidacion",
            ),
        ),
        migrations.AddField(
            model_name="ajustecomision",
            name="vendedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
