# Generated by Django 5.2.17 on 2026-09-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="debe_cambiar_clave",
            field=models.BooleanField(
                default=False,
                help_text="Se activa al asignar una contraseña temporal; se pide cambiarla al entrar.",
                verbose_name="Debe cambiar la contraseña",
            ),
        ),
    ]
