# Generated by Django 5.2.17 on 2026-09-30 17:40

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("empresas", "0002_perfilempresa_vendedores_ven_todos_los_clientes"),
        ("inventario", "0004_importacionproductos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Presupuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=30, verbose_name="Número")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("EMITIDO", "Emitido"),
                            ("APARTADO", "Apartado"),
                            ("POR_VALIDAR", "Por validar"),
                            ("VALIDADA", "Venta validada"),
                            ("RECHAZADA", "Rechazada"),
                            ("VENCIDO", "Apartado vencido"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="BORRADOR",
                        max_length=12,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Fecha"
                    ),
                ),
                ("valido_hasta", models.DateField(verbose_name="Válido hasta")),
                (
                    "tasa_bs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Tasa BCV al emitir. Se congela para este documento.",
                        max_digits=14,
                        null=True,
                        verbose_name="Tasa Bs/USD",
                    ),
                ),
                (
                    "iva_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("16.00"),
                        max_digits=5,
                        verbose_name="IVA (%)",
                    ),
                ),
                (
                    "descuento_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Descuento (%)",
                    ),
                ),
                (
                    "subtotal_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "descuento_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "base_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "iva_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_bs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "requiere_revision",
                    models.BooleanField(
                        default=False, verbose_name="Precio fuera de rango"
                    ),
                ),
                (
                    "apartado_hasta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Apartado hasta"
                    ),
                ),
                ("confirmado_en", models.DateTimeField(blank=True, null=True)),
                ("validado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "motivo_rechazo",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Motivo del rechazo"
                    ),
                ),
                ("pagado", models.BooleanField(default=False, verbose_name="Pagado")),
                (
                    "fecha_pago",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de pago"
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TRANSFERENCIA", "Transferencia"),
                            ("PAGO_MOVIL", "Pago móvil"),
                            ("EFECTIVO_USD", "Efectivo USD"),
                            ("EFECTIVO_BS", "Efectivo Bs"),
                            ("ZELLE", "Zelle"),
                            ("PUNTO", "Punto de venta"),
                            ("MIXTO", "Mixto"),
                            ("CREDITO", "Crédito"),
                        ],
                        max_length=15,
                        verbose_name="Método de pago",
                    ),
                ),
                (
                    "entregado",
                    models.BooleanField(default=False, verbose_name="Entregado"),
                ),
                (
                    "fecha_entrega",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de entrega"
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas internas")),
                (
                    "condiciones",
                    models.TextField(blank=True, verbose_name="Condiciones (PDF)"),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="presupuestos",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "validado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Presupuesto / venta",
                "verbose_name_plural": "Presupuestos y ventas",
                "ordering": ["-creado_en", "-pk"],
                "base_manager_name": "todos",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ItemPresupuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "precio_base_usd",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Precio de lista"
                    ),
                ),
                (
                    "precio_usd",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Precio"
                    ),
                ),
                (
                    "costo_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Costo de referencia",
                    ),
                ),
                ("fuera_de_rango", models.BooleanField(default=False)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventario.producto",
                    ),
                ),
                (
                    "presupuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ventas.presupuesto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem",
                "verbose_name_plural": "Ítems",
                "ordering": ["orden", "pk"],
                "base_manager_name": "todos",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="ventas.itempresupuesto",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventario.lote",
                    ),
                ),
            ],
            options={
                "base_manager_name": "todos",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="presupuesto",
            index=models.Index(
                fields=["empresa", "estado", "validado_en"], name="venta_estado_fecha"
            ),
        ),
        migrations.AddIndex(
            model_name="presupuesto",
            index=models.Index(
                fields=["empresa", "vendedor", "estado"], name="venta_vendedor_estado"
            ),
        ),
        migrations.AddConstraint(
            model_name="presupuesto",
            constraint=models.UniqueConstraint(
                fields=("empresa", "numero"), name="presupuesto_numero_unico"
            ),
        ),
    ]
