# Generated by Django 5.2.17 on 2026-10-01 17:12

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0004_alter_membresia_options"),
        ("inventario", "0005_alter_movimientoinventario_tipo"),
        ("ventas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="presupuesto",
            name="devuelto_usd",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=14, verbose_name="Devuelto"
            ),
        ),
        migrations.AlterField(
            model_name="presupuesto",
            name="estado",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("EMITIDO", "Emitido"),
                    ("APARTADO", "Apartado"),
                    ("POR_VALIDAR", "Por validar"),
                    ("VALIDADA", "Venta validada"),
                    ("RECHAZADA", "Rechazada"),
                    ("VENCIDO", "Apartado vencido"),
                    ("CANCELADO", "Cancelado"),
                    ("DEVUELTA", "Devuelta"),
                ],
                default="BORRADOR",
                max_length=12,
                verbose_name="Estado",
            ),
        ),
        migrations.CreateModel(
            name="Devolucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=30, verbose_name="Número")),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Fecha"
                    ),
                ),
                ("motivo", models.CharField(max_length=250, verbose_name="Motivo")),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                (
                    "subtotal_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "descuento_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "base_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "iva_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_bs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "reembolsado",
                    models.BooleanField(default=False, verbose_name="Reembolsado"),
                ),
                (
                    "reembolso_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Monto reembolsado (USD)",
                    ),
                ),
                (
                    "reembolso_metodo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TRANSFERENCIA", "Transferencia"),
                            ("PAGO_MOVIL", "Pago móvil"),
                            ("EFECTIVO_USD", "Efectivo USD"),
                            ("EFECTIVO_BS", "Efectivo Bs"),
                            ("ZELLE", "Zelle"),
                            ("PUNTO", "Punto de venta"),
                            ("MIXTO", "Mixto"),
                            ("CREDITO", "Crédito"),
                        ],
                        max_length=15,
                        verbose_name="Método",
                    ),
                ),
                (
                    "reembolso_fecha",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha del reembolso"
                    ),
                ),
                (
                    "reembolso_referencia",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Referencia"
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "presupuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devoluciones",
                        to="ventas.presupuesto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devolución",
                "verbose_name_plural": "Devoluciones",
                "ordering": ["-creada_en", "-pk"],
                "base_manager_name": "todos",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ItemDevolucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "reingresa",
                    models.BooleanField(
                        default=True, verbose_name="Vuelve al inventario"
                    ),
                ),
                (
                    "subtotal_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "devolucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ventas.devolucion",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devoluciones",
                        to="ventas.itempresupuesto",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventario.lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem devuelto",
                "verbose_name_plural": "Ítems devueltos",
                "ordering": ["pk"],
                "base_manager_name": "todos",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="devolucion",
            constraint=models.UniqueConstraint(
                fields=("empresa", "numero"), name="devolucion_numero_unico"
            ),
        ),
    ]
