# Generated by Django 5.2.17 on 2026-10-01 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("empresas", "0004_alter_membresia_options"),
        ("ventas", "0002_devoluciones"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="presupuesto",
            name="facturado",
            field=models.BooleanField(default=False, verbose_name="Facturado"),
        ),
        migrations.AddField(
            model_name="presupuesto",
            name="fecha_facturacion",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de facturación"
            ),
        ),
        migrations.AddField(
            model_name="presupuesto",
            name="numero_control",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="N° de control"
            ),
        ),
        migrations.AddField(
            model_name="presupuesto",
            name="numero_factura",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="N° de factura"
            ),
        ),
        migrations.AddIndex(
            model_name="presupuesto",
            index=models.Index(fields=["empresa", "facturado"], name="venta_facturado"),
        ),
    ]
