# Generated by Django 5.2.17 on 2026-10-04 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("empresas", "0005_formato_numero_presupuesto"),
        ("ventas", "0003_facturacion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="presupuesto",
            name="presupuesto_numero_unico",
        ),
        migrations.AlterField(
            model_name="presupuesto",
            name="numero",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="Número"
            ),
        ),
        migrations.AddConstraint(
            model_name="presupuesto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("numero", ""), _negated=True),
                fields=("empresa", "numero"),
                name="presupuesto_numero_unico",
            ),
        ),
    ]
