# Generated by Django 5.2.17 on 2026-10-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0004_numero_al_guardar"),
    ]

    operations = [
        migrations.AddField(
            model_name="presupuesto",
            name="banco_pago",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="Banco emisor"
            ),
        ),
        migrations.AddField(
            model_name="presupuesto",
            name="moneda_pago",
            field=models.CharField(
                blank=True,
                choices=[("USD", "USD"), ("BS", "Bs")],
                max_length=3,
                verbose_name="Moneda del pago",
            ),
        ),
        migrations.AddField(
            model_name="presupuesto",
            name="monto_pago",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=18,
                null=True,
                verbose_name="Monto recibido",
            ),
        ),
        migrations.AddField(
            model_name="presupuesto",
            name="referencia_pago",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Referencia"
            ),
        ),
    ]
