# Generated by Django 5.2.17 on 2026-10-04 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0006_estado_por_pagar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="presupuesto",
            name="pago_registrado_en",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Pago registrado el"
            ),
        ),
        migrations.AddField(
            model_name="presupuesto",
            name="pago_registrado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Pago registrado por",
            ),
        ),
    ]
