# Generated by Django 5.2.17 on 2026-10-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0007_pago_registrado_por"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presupuesto",
            name="estado",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("EMITIDO", "Emitido"),
                    ("APARTADO", "Apartado"),
                    ("POR_PAGAR", "Por cobrar"),
                    ("POR_VALIDAR", "Por validar"),
                    ("VALIDADA", "Venta validada"),
                    ("RECHAZADA", "Rechazada"),
                    ("VENCIDO", "Apartado vencido"),
                    ("CANCELADO", "Cancelado"),
                    ("DEVUELTA", "Devuelta"),
                ],
                default="BORRADOR",
                max_length=12,
                verbose_name="Estado",
            ),
        ),
    ]
