# Generated by Django 5.2.17 on 2026-10-08 00:30

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0005_formato_numero_presupuesto"),
        ("ventas", "0008_etiqueta_por_cobrar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="itempresupuesto",
            name="exento_iva",
            field=models.BooleanField(default=False, verbose_name="Exento de IVA"),
        ),
        migrations.AddField(
            model_name="presupuesto",
            name="exento_usd",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name="Despacho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Fecha de despacho",
                    ),
                ),
                (
                    "direccion_entrega",
                    models.TextField(blank=True, verbose_name="Dirección de entrega"),
                ),
                (
                    "transportista",
                    models.CharField(
                        max_length=120, verbose_name="Nombre del transportista"
                    ),
                ),
                (
                    "cedula",
                    models.CharField(blank=True, max_length=20, verbose_name="Cédula"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Teléfono"
                    ),
                ),
                (
                    "empresa_transporte",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Empresa de transporte"
                    ),
                ),
                (
                    "vehiculo",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Vehículo (marca, modelo, color)",
                    ),
                ),
                ("placa", models.CharField(max_length=15, verbose_name="Placa")),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "con_precios",
                    models.BooleanField(
                        default=True, verbose_name="Mostrar precios y totales"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "presupuesto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="despacho",
                        to="ventas.presupuesto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de despacho",
                "verbose_name_plural": "Notas de despacho",
                "base_manager_name": "todos",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
    ]
