# Generated by Django 5.2.17 on 2026-10-09 15:42

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def pagos_a_abonos(apps, schema_editor):
    """Cada venta ya pagada pasa a tener un abono por su total: nada cambia para el usuario."""
    Presupuesto = apps.get_model('ventas', 'Presupuesto')
    Abono = apps.get_model('ventas', 'Abono')
    nuevos = []
    for p in Presupuesto.objects.filter(pagado=True).iterator():
        neto = p.total_usd - p.devuelto_usd
        tasa = None
        if p.moneda_pago == 'BS' and p.monto_pago:
            tasa = p.tasa_bs or None
        nuevos.append(Abono(
            empresa_id=p.empresa_id, presupuesto_id=p.pk, fecha=p.fecha_pago or p.fecha, metodo=p.metodo_pago or 'TRANSFERENCIA',
            banco=p.banco_pago, referencia=p.referencia_pago,
            moneda=p.moneda_pago if p.monto_pago is not None and p.moneda_pago else 'USD',
            monto=p.monto_pago if p.monto_pago is not None else neto, tasa_bs=tasa, monto_usd=neto,
            registrado_por_id=p.pago_registrado_por_id))
        if len(nuevos) >= 500:
            Abono.objects.bulk_create(nuevos)
            nuevos = []
    Abono.objects.bulk_create(nuevos)
    from django.db.models import F
    Presupuesto.objects.filter(pagado=True).update(abonado_usd=F('total_usd') - F('devuelto_usd'))


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0006_ocultar_sin_stock"),
        ("ventas", "0009_exento_y_despacho"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="presupuesto",
            name="abonado_usd",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=14, verbose_name="Abonado (USD)"
            ),
        ),
        migrations.CreateModel(
            name="Abono",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Fecha"
                    ),
                ),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("TRANSFERENCIA", "Transferencia"),
                            ("PAGO_MOVIL", "Pago móvil"),
                            ("EFECTIVO_USD", "Efectivo USD"),
                            ("EFECTIVO_BS", "Efectivo Bs"),
                            ("ZELLE", "Zelle"),
                            ("PUNTO", "Punto de venta"),
                            ("MIXTO", "Mixto"),
                            ("CREDITO", "Crédito"),
                        ],
                        max_length=15,
                        verbose_name="Método",
                    ),
                ),
                (
                    "banco",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Banco emisor"
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Referencia"
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        choices=[("USD", "USD"), ("BS", "Bs")],
                        default="USD",
                        max_length=3,
                        verbose_name="Moneda",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="Monto"
                    ),
                ),
                (
                    "tasa_bs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="Tasa Bs/USD",
                    ),
                ),
                (
                    "monto_usd",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Equivale (USD)"
                    ),
                ),
                ("registrado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "presupuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonos",
                        to="ventas.presupuesto",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Abono",
                "verbose_name_plural": "Abonos",
                "ordering": ["fecha", "pk"],
                "base_manager_name": "todos",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(pagos_a_abonos, migrations.RunPython.noop),
]
