# Generated by Django 5.2.17 on 2026-10-09 16:40

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0006_ocultar_sin_stock"),
        ("ventas", "0010_abonos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transportista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120, verbose_name="Nombre")),
                (
                    "cedula",
                    models.CharField(blank=True, max_length=20, verbose_name="Cédula"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Teléfono"
                    ),
                ),
                (
                    "empresa_transporte",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Empresa de transporte"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transportista",
                "verbose_name_plural": "Transportistas",
                "ordering": ["nombre", "pk"],
                "base_manager_name": "todos",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placa", models.CharField(max_length=15, verbose_name="Placa")),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Vehículo (marca, modelo, color)",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehículo",
                "verbose_name_plural": "Vehículos",
                "ordering": ["placa", "pk"],
                "base_manager_name": "todos",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("empresa", "placa"), name="vehiculo_placa_unica"
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
    ]
